### ISSUE TITLE
Stale reference to proposal-realms/shim

### ISSUE THREAD

**Issue by erights** [Agoric/SES#104]
We should change

https://github.com/Agoric/SES/blob/18b937dd7d3abc8df80186ea43ebf331e3705bc8/src/index.js#L17

from `proposal-realms/shim/` to `realms-shim/`

**Comment by katelynsills** [comment]
I think once we have the realms-shim published on npm, which should be soon, we will be rewriting all of the references to point to the package itself rather than the realms-shim repo as a submodule.

**Comment by warner** [comment]
Yeah. Another intermediate option is to point our submodule at `agoric/realms-shim` instead of `tc30/proposal-realms`, and then change the internal pathname to match. In either case, the submodule is pinned to a specific git revision hash, so we're insensitive to the changes that happened in subsequent revisions.

**Comment by katelynsills** [comment]
Maybe I'm misunderstanding, but is there a reason that we would prefer the submodule version the npm package? I tend to prefer the npm package approach so that we can model how to use the shim in the same way that other people will use it. Plus, we can pin the version  if we need to, giving us the same protection against changes. But I could be missing something?
