### ISSUE TITLE
Remove "old" files

### ISSUE THREAD

**Issue by katelynsills** [Agoric/SES#108]
We have a directory called `old` which isn't in use. Since we have version control, I think we should take it out. Otherwise, it gets a little confusing. For instance, when I was making the change to use the realms-shim repo as a submodule, it was not clear whether I needed to update `src/old/tamperProof.js` or not.

**Comment by warner** [comment]
@erights: this directory contains some files from the caja repository that we haven't yet incorporated into SES, I didn't want to delete them entirely without doing a pass to see what we wanted to port over. `ejectorsGuardsTrademarks.js` in particular. Could you take a look at https://github.com/Agoric/SES/tree/0.5.0/src/old and file tickets for anything that you think we should plan to incorporate in modern SES?

I'll delete this directory now, we can mine the code from git history if/when we do that port, and the link above will remain valid since it points to the last tagged release.

**Comment by warner** [comment]
ok I really should have just filed an issue for that. Mark, look at #121 instead. Closing this one now that the files are deleted.
