### ISSUE TITLE
Endowments are not on the global

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#123]
Since endowments are not accessible on the global it is not possible to match some unsandboxed behavior.

browser example:
```js
this.postMessage === postMessage
//=> true
SES.makeSESRootRealm().evaluate('this.postMessage === postMessage', { postMessage })
//=> false
```
nodejs example
```js
this.process === process
//=> true
SES.makeSESRootRealm().evaluate('this.process === process', { process })
//=> false
```

**Comment by erights** [comment]
Yes. I've been meaning to mention that (especially as this is currently a difference with the XS/tc53 Compartment API).

background:

The endowments are per-evaluation, and emulate the so-called "global lexical scope", which is closer than the global scope, and which does not correspond to properties on any reified object. (In our shim implementation, they are properties on an internal object, but this object is never revealed.) Outside of the realms and SES shims, AFAIK, no one has ever used the global lexical scope on purpose. It was introduced to the EcmaScript spec to account for top-level `let`, `const`, and IIRC `class` declarations, so that they can be shared between scripts without becoming global properties. (Personal note: IMO this entire design was probably a very bad idea, but I did not object at the time, when it would have made a difference.)

end background

It is important for us that different evaluations can share the same global while having different endowments. This makes it possible for us to emulate the CommonJS module system, where different modules at different locations in the relative module naming system can be endowed with different `require` functions and `module` objects while sharing the same global.

The workaround for now: After you make a root realm or compartment, but before you evaluate user code in that root realm or compartment, copy the desired global properties onto that global object:

```js
Object.assign(realm.global, globalEndowments);
```
or
```js
Object.defineProperties(realm.global, Object.getPropertyDescriptors(globalEndowments));
```
The first will only copy enumerable properties, and will invoke getters of accessor properties of the `globalEndowments`. The latter with copy all own properties, and will create new accessors that mimic the old accessors, by reusing the old accessor's getter and setter functions. I would generally recommend the latter, though it should rarely make a difference.

Please let me know if this helps.

**Comment by kumavis** [comment]
@erights thanks for the thorough response

> It is important for us that different evaluations can share the same global while having different endowments. 

hmm, I hadn't considered this requirement. Why is it important to share the same global if the global is immutable?

> This makes it possible for us to emulate the CommonJS module system, where different modules at different locations in the relative module naming system can be endowed with different require functions and module objects while sharing the same global.

I see.  Though I still don't understand the sharing the global requirement.
by the way, If you're curious, read below on how browserify handles "require".

### how "require" works in browserify 

in `browserify` (with and without `sesify`) commonjs modules are evaluated inside a wrapper fn
```js
(function(require,module,exports){
   // original module source goes here...
})
``` 
In `sesify` this goes into `SES` 
```js
const moduleInitializer = rootRealm.evaluate(src, packageEndowments)
```
and `moduleInitializer` is called with a require function that has context of the module being defined so it knows what dependencies it can use

`browserify`'s approach here **doesnt** respect nodejs's scope semantics, but oh well
```bash
➜ echo 'console.log(this.require === require)' | node               
true
➜ echo 'console.log(this.require === require)' | browserify - | node 
false
```

### potential workaround in sesify

Assuming the only way to access the global is with a top-level `this`, in `sesify` we control all access to the global.
Since module code runs inside a module definition wrapper with `this` set to `module.exports` (correct nodejs + browserify semantics), top-level `this` is not available.

Currently we add references (`self` and `window`) to the global you would expect in the browser.
```js
const self = this; const window = this;
(function(require,module,exports){
   // original module source goes here...
})
``` 

We could modify these references to use a fake global that combines endowments and the real global.
```js
const self = {}, window = self;
Object.defineProperties(self, Object.getOwnPropertyDescriptors(_endowments))
Object.defineProperties(self, Object.getOwnPropertyDescriptors(this))
(function(require,module,exports){
   // original module source goes here...
})
```

**Comment by kumavis** [comment]
> The workaround for now: After you make a root realm or compartment, but before you evaluate user code in that root realm or compartment, copy the desired global properties onto that global object:

```js
> SES=require('ses')
{ makeSESRootRealm: [Function: makeSESRootRealm] }
> realm = SES.makeSESRootRealm()
Realm { makeRequire: [Function: makeRequire] }
> Object.assign(realm.global, {a:3})
Thrown:
TypeError: Cannot add property a, object is not extensible
    at TamedFunction.assign (<anonymous>)
```
```
➜ cat node_modules/ses/package.json| jq .version
"0.5.0"
```

**Comment by kumavis** [comment]
Needs to happen on a compartment

```
> SES=require('ses')
{ makeSESRootRealm: [Function: makeSESRootRealm] }
> realm = SES.makeSESRootRealm()
Realm { makeRequire: [Function: makeRequire] }
> c1 = realm.global.Realm.makeCompartment()
Realm {}
> Object.assign(c1.global, {a:1})
{ a: 1 }
```

**Comment by erights** [comment]
Yes, only a compartment's global. The global of an SES root realm must be immutable.

**Comment by kumavis** [comment]
closing as not-a-bug
