### ISSUE TITLE
Support consistent "harden" and "Nat" usage in and out of SES

### ISSUE THREAD

**Issue by dtribble** [Agoric/SES#13]
There are several use cases for having the same source work both within SES and outside it:

* library code that could be used in both cases
* unit test of code in test framework that doesn't use SES
* debugging code in a small repro

Both `def` and `Nat` may appear in SES code, which currently will not work in a non-SES environment.

Additionally `console.log` should be usable as well.  That's a related but structurally different issue.

**Comment by warner** [comment]
Some notes: while experimenting with this, we tried exporting `def` (which does a recursive "deep freeze", calling `Object.freeze` on its argument and anything reachable via property lookup or the prototype chain). In an SES environment, this is fine and exactly what you want, and doesn't take very long because all the primordials are already frozen (i.e. the traversal ends when it reaches `Object.prototype`). But outside an SES environment, the real `def` would freeze the *entire* environment, including all the primordials of the primal realm, which is surprising at best, and would probably break some code that expects to be able to mutate such things.

So part of the hack that @dtribble and @erights put together is a switch inside `def` that tries to determine whether it's inside a SES environment or not, and if not then it merely does a *shallow* freeze, instead of doing the full transitive closure. The thought was that this would probably catch some basic bugs (mutating the surface of an object that's been passed through `def()`), without breaking the whole environment.

**Comment by erights** [comment]
The hack in question is currently at
https://github.com/Agoric/SES/blob/master/src/bundle/def.js

This relates to
https://github.com/tc39/proposal-decorators/pull/139

The issue in both places is, what should it mean to have a *defensible api surface* and in a *defensible class* within a non-frozen realm? We should continue to have `def` indicate *define defensible objects* to the extent that makes any sense outside a frozen realm. While not freezing that realm's primordials, that SES should still somehow be transitive. However, it can differ from `deepFreeze` further if it needs to.

I propose that the "stopping weakmap" for `def` in a non-frozen realm be initialized to that realm's primordials, even though they aren't themselves defensible. Of course, `deepFreeze` must not do this, so that `deepFreeze` can still free the primordials of a realm intended to be frozen after shim customization.

Given that, our old definition of a defensible class stands, except we need to revisit the issue of what a defensible class can inherit from. But a defensible class in a non-frozen realm should be able to inherit from a non-frozen primordial. This allows us to avoid cauterizing the PrivateName of https://github.com/tc39/proposal-decorators/pull/139 while still letting it be equivalent to a defensible class.

**Comment by erights** [comment]
Note that `def` is likely to be renamed `harden`. See https://github.com/Agoric/SES/issues/15#issuecomment-451363507
