### ISSUE TITLE
Setting prototype via "__proto__" not supported under SES

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#133]
Setting prototype via `x.__proto__ = y` not supported under SES.

```js
r = require('ses').makeSESRootRealm()

assignProto = `class A {}; A.prototype.x = 1; var a = {};  a.__proto__ = A.prototype; a.x`
setProto = `class A {}; A.prototype.x = 1; var a = {};  Object.setPrototypeOf(a, A.prototype); a.x`

sesAssign = r.evaluate(assignProto)
sesSet = r.evaluate(setProto)
evalAssign = eval(assignProto)
evalSet = eval(setProto)

console.log({ 
  sesAssign, // undefined
  sesSet,  // 1
  evalAssign, // 1
  evalSet, //1
})
```

possibly related? #116

**Comment by kumavis** [comment]
`__proto__` has been the source of [prototype pollution attacks](https://medium.com/@daniakash/what-is-prototype-pollution-and-why-is-it-such-a-big-deal-2dd8d89a93c) so I can understand that this might be intentionally disabled

if intentional, it should be added to documentation somewhere

**Comment by erights** [comment]
Thanks for catching this. It is a bug. At https://github.com/Agoric/SES/blob/21306b42cb53a8283c325c12af784c842895b4c8/src/bundle/whitelist.js#L276
we see
```js
        // __proto__: t, whitelisted manually in startSES.js
```
but there is no startSES.js in modern SES. Rather, this is a reference to
https://github.com/google/caja/blob/master/src/com/google/caja/ses/startSES.js
in the old Caja ES5-oriented implementation of SES.

Modern SES is trying to be, approximately, the maximal subset of JavaScript, that can accept as much old code as possible without compromising ocap-safety. Since it does whitelist `setPrototypeOf`, there would be little point in not whitelisting `__proto__`.

Your example indeed shows a hazard that arises from non whitelisting it. Code that used to use it does not produce a clean error due to its absence. Rather, your assignment 
```js
a.__proto__ = A.prototype;
```
became a simple assignment, giving `a` an ordinary own property whose name happens to be `__proto__`. This kind of silent divergence from programmer expectation at runtime is a much worse hazard than are whatever we might accomplish from omitting this.

**Comment by erights** [comment]
Started at #134
