### ISSUE TITLE
SES in SES

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#155]
if someone tries to bring their own SES to ensure they have a safe environment to work with, but ends up running in a SES environment, it should still work somehow.

currently it fails with:
> possible direct eval expression rejected around line 673

Which refers to:
```js
const unsafeGlobal = iframe.contentWindow.eval(unsafeGlobalSrc);
```
In: `createNewUnsafeGlobalForBrowser`

cc @rekmarks @erights

**Comment by erights** [comment]
This is not actually a direct eval. If it were rewritten so that it doesn't trigger the conservative direct eval detector

```js
const unsafeGlobal = (1, iframe.contentWindow.eval)(unsafeGlobalSrc);
```

that would get past the immediate problem you ran into. However, you will then run into an unfixable conflict with `with`. The [8 magic lines of code](https://www.youtube.com/watch?v=mSNxsn0pK74&list=PLKr-mvz8uvUg70w0yKGfytaDqxiIBNo_L) at the heart of the Realms shim cannot be implemented without "with" which exists only in sloppy code. The Realms shim and SES does not and cannot allow any sloppy code. 

Closing this one, because the literal request here is impossible.

In out-of-band conversation, it seems you may want something possible (even likely easy), so feel free to filing a new issue clarifying that.
