### ISSUE TITLE
Problem escaping double quotes

### ISSUE THREAD

**Issue by scull06** [Agoric/SES#168]
Hello,

I'm facing problems when the program escape double quotes.  For example, evaluating the following:

```
const SES = require("ses");
const realm = SES.makeSESRootRealm({ consoleMode: "allow", errorStackMode: 'allow' });
realm.evaluate('console.log(" some string  \" more string \" yet more ");');
```

will give a syntax error (**SyntaxError: missing ) after argument list**), however, if the   **\\"**  are removed then it works.

**Comment by michaelfig** [comment]
You'll notice that this is not SES-specific:

```js
eval('console.log(" some string  \" more string \" yet more ");');
```

throws a SyntaxError as you describe.

You actually need:

```js
eval('console.log(" some string  \\" more string \\" yet more ");')
```

If you think of it, it's because you need a backslash to appear before the double-quote in the outer string:

```
console.log('\"'); //=> "
console.log('\\"'); //=> \"
```

You could also use template literals to avoid most of this problem:

```
realm.evaluate(`console.log(' some string  " more string " yet more ');`);
```

Good luck!
