### ISSUE TITLE
1001 Iframes

### ISSUE THREAD

**Issue by kumavis** [Agoric/SES#23]
hello I'm experimenting with SES and found that on the creation of the 1001st iframe, the `iframe.contentWindow` is `null` and throws an error in `createNewUnsafeGlobalForBrowser`

this is in chrome

when can the iframes be garbage collected?

**Comment by erights** [comment]
Hi @kumavis , I don't know, but it might be productive to look at how [test262](https://github.com/tc39/test262) works in the browser. IIUC, it creates a tremendous number of iframes for running the tests. I expect it destroys each one manually rather than leaving to the garbage collector, but I don't know.

Hi @leobalter , so what does test262 do with collection of iframes? Thanks.

Hi @ajklein , under what conditions does Chrome garbage collect an iframe? Please forward to whoever can answer. Thanks.

**Comment by leobalter** [comment]
@erights Test262 tests limits themselves to ecma-262 (+ JSON and ecma-402) specs so it does not use things like iframes or anything from browser APIs.

There is a web runner currently maintained in an external project by @bakkot who might have some insights about the iframes usage.

Other current runners are not relying on browsers but the engines themselves. I've also been early experimenting with webdriver that provides a way I can fully avoid iframes and load independent instances.

**Comment by bakkot** [comment]
My [web runner](https://github.com/bakkot/test262-web-runner/) just reuses a small number (currently 4) of frames, resetting them with `.src = ''` between tests. I don't remember if I had issues with creating large numbers of frames, but it was certainly a lot slower than reusing existing ones.

**Comment by ajklein** [comment]
This doesn't seem related to collection, it's rather a hard limit imposed on subframe creation: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/html_frame_owner_element.cc?rcl=c9094c99449adbde1ed817b9c3af33cd9b07506d&l=378

**Comment by erights** [comment]
Aha! I see the constant is defined at 
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/page/page.h?g=0&l=267
Thanks.

**Comment by erights** [comment]
Labeled this "question" and closing as the thread provides the two relevant answers:

   * At https://github.com/Agoric/SES/issues/23#issuecomment-451637503 @kumavis reports now reusing a single SES root realm, which is the right way to use SES anyway when that fits.

   * At https://github.com/Agoric/SES/issues/23#issuecomment-452076643 @ajklein reports that this limit is hard coded into Chromium, rather than emergent from resource allocation/collection behavior.
