### ISSUE TITLE
write basic usage docs

### ISSUE THREAD

**Issue by warner** [Agoric/SES#66]
per #64 we really need some warmup docs

**Comment by warner** [comment]
In a Node.js repl, after running `npm install ses`:

```js
const SES = require('ses');
const s = SES.makeSESRootRealm({consoleMode: 'allow', errorStackMode: 'allow'});
// NOTE: errorStackMode enables confinement breach, do not leave on in production
s.evaluate('1+2'); // returns 3
s.evaluate('1+a', {a: 3}); // returns 4
function double(a) {
  return a*2;
]
const doubler = s.evaluate(`(${double})`);
doubler(3); // returns 6
```

In an HTML page's `<head>` section (see demo/ for something functional), this adds an `SES` symbol to the global scope:
```html
<script src=".../dist/ses-shim.js"></script>
```

then after that loads (e.g. in a `<script>` tag at the end of the `<body>`), the following code should work:

```js
const s = SES.makeSESRootRealm(...);
s.evaluate(...);
```

Note that the Realm shim currently requires either the Node.js `vm` module, or a browser's `<iframe>` element (it does `document.createElement('iframe')`), so it won't work in a DOM-less `WebWorker`, `SharedWorker`, or `ServiceWorker`. If/when the Realms proposal becomes a standard part of Javascript, these environments ought to have a native `Realm` object available, and SES should work in all of them.

**Comment by dckc** [comment]
hmm... I would expect the example above to go in the README. "Run the test suite" is for developers of SES; it goes in CONTRIBUTING.md, if you're talking to the usual npm audience.

Also, the "getting started" example should exercise at least one novel feature of SES such as showing how, unlike normal eval, realm.evaluate doesn't give access to the dynamic scope. Something like a "send all the bitcoins to me" function that fails because XmlHttpRequest is not in scope or something.
