### ISSUE TITLE
Which URL for the challenge demo page?

### ISSUE THREAD

**Issue by erights** [Agoric/SES#7]
https://github.com/Agoric/SES/blob/master/README.md links to https://cdn.rawgit.com/Agoric/SES/0.0.1/demo/ but https://github.com/Agoric/SES/blob/master/demo/README.md links to https://rawgit.com/Agoric/SES/master/demo/

Orthogonally, should the default have the attack enabled or disabled? In my talk I linked to the url with `?dateNow=enabled` because I think it plays better to first see the attack in action before having the enablers removed.

**Comment by warner** [comment]
The CDN link should be able to handle more traffic, but it's tied to a specific version (the CDN stores an immutable copy, indexed by the tag). I asked Kate to point at the CDN flavor for the PoW newsletter.

I left the demo/README pointed at the mutable version (rawgit.com instead of cdn.rawgit.com) so if you follow the demo link by browsing github, you'll get to a version that matches the code you were just browsing.

I'm up in the air about whether the initial link should enable or disable Date.now. If we're walking someone through it, then yeah we should start with it enabled. But the default for SES will have it disabled, so it might be more "accurate" to have that be the defualt.

**Comment by erights** [comment]
They both link directly to https://rawgit.com/Agoric/SES/master/demo/ . Closing.
