### ISSUE TITLE
ses@0.4.0 fails with Node.js 8

### ISSUE THREAD

**Issue by michaelfig** [Agoric/SES#72]
This fails:

```sh
$ npm install ses
$ node
> ses = require('SES');
file:///Users/michael/src/self/jessica/lang/nodejs/node_modules/ses/src/bundle/anonIntrinsics.js:106
  async function* aStrictAsyncGenerator() {} // eslint-disable-line no-empty-function
                ^
SyntaxError: Unexpected token *

>
$ node --version
v8.11.1
$
```

Any advice?

**Comment by erights** [comment]
Should we require as a minimum a more recent node version that does support that syntax?

If there is a reason to support older versions of Node instead, we could use `eval` to test if that syntax is supported, and then place the relevant block of code inside an `if`. Is there a good reason to do that?

**Comment by michaelfig** [comment]
Yes, if indeed a more recent Node works, I would gladly use that instead.  Then, the SES `package.json` should enforce the requirement.

However, I don't see any compelling reason why SES should not work with earlier Nodes.  Portability is laudable.

**Comment by warner** [comment]
I think Node 9 is the minimum required version (at least that's what our automated tests exercise), until we add the kind of conditional block MarkM described.

**Comment by warner** [comment]
Huh, node-9.11.2 fails to parse `async function* aStrictAsyncGenerator`.. but I think we've stopped building with travis, and now we're only using CircleCI, and I don't think we're using anything other than Node 11 there.

I'll add a ticket to exercise multiple versions of Node on CircleCI, and to try to conditionally build `aStrictGenerator` and `aStrictAsyncGenerator` inside an `eval()`.

**Comment by warner** [comment]
I've got a branch (`72-older-syntax`) that adds this conditional check, but it's failing everywhere right now because `esm` is rewriting the `eval()` to something unexpected. The error looks like:

```
ReferenceError: _12c‍ is not defined
    at getAnonIntrinsics (eval at <anonymous> (eval at createScopedEvaluatorFactory (/home/warner/bindmounts/trees/SES/proposal-realms/shim/src/evaluators.js:59:10)), <anonymous>:61:5)
```

and I believe it's happening in the line of `getAnonIntrinsics` that uses the `eval`:

```js
  try {
    aStrictAsyncGenerator = eval('(async function* () {})');
    haveAsyncGenerators = true;
  } catch (e) {
    if (!(e instanceof SyntaxError)) {
      throw e;
    }
    // a SyntaxError from that eval means this engine doesn't support async
    // generators, e.g. Node 9 or older
  }
```

I'll keep experimenting to see if there's a way to avoid that. One technique would be to pass in an async generator, except that `getAnonIntrinsics` is called twice (once for repair, then again later for freezing), and there isn't a great way to pass in a value in both places. Another technique might be to perform the "do we have this syntax" check externally and then evaluate a separate (smaller) `getAsyncGeneratorIntrinsic` module iff that syntax is available (in which the `async function*` appears unprotected by an `eval` block), but that's non-trivial too.

**Comment by michaelfig** [comment]
I am withdrawing this issue, given that Node.js 10 is the new LTS version, and switching to it is not difficult.  I've verified that Node 10 works just fine.

Please reopen only if you think Node.js 8 should actually be supported.
